version: '3.8'

services:
  api:
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  worker:
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - api
    environment:
      API_URL: api
